name: custom_language_picker
description: "A customizable language picker for Flutter with modern UI, storage support, and emoji flags."
version: 0.0.1
homepage: https://github.com/yourusername/custom_language_picker

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1    # State yönetimi için
  shared_preferences: ^2.2.2    # Yerel depolama için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # Eğer bayrak görselleri kullanacaksanız assetleri ekleyin
  assets:
    - assets/