name: custom_language_picker
description: "A customizable language picker for Flutter with modern UI, storage support, and emoji flags."
version: 0.0.2
homepage: https://github.com/SametDemirtas/custom_language_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
# To add assets to your package, add an assets section like this:
# assets:
#   - assets/